[build-system]
requires = [
  "scikit-build-core>=0.10",
  "torch>=2.8.0",
  "wheel",
]
build-backend = "scikit_build_core.build"

[project]
name = "sglang-kernel"
dynamic = ["version"]
authors = [
  { name="SGLang Kernel Team", email="sglang@lmsys.org" },
]
description = "Kernel Library for SGLang"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Environment :: GPU :: NVIDIA CUDA"
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/sgl-project/sglang/tree/main/python/sglang/kernels/aot"
"Bug Tracker" = "https://github.com/sgl-project/sglang/issues"

[tool.wheel]
exclude = [
  "dist*",
  "tests*",
]

[tool.scikit-build]
cmake.build-type = "Release"
minimum-version = "build-system.requires"

wheel.py-api = "cp310"
wheel.license-files = []
wheel.packages = ["python/sgl_kernel"]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "../sgl_kernel_version.py"
regex = '''SGL_KERNEL_VERSION\s*=\s*["'](?P<value>[^"']+)["']'''
